ALTER TABLE chat_settings
    ADD COLUMN IF NOT EXISTS clean_service_title BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS clean_service_photo BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS clean_service_other BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS clean_service_videochat BOOLEAN NOT NULL DEFAULT FALSE;
