ALTER TABLE captcha_settings
    ADD COLUMN IF NOT EXISTS rules_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS auto_unmute_seconds INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS kick_on_timeout BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS button_text TEXT NOT NULL DEFAULT 'Click here to prove you''re human';

ALTER TABLE captcha_challenges
    ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'button',
    ADD COLUMN IF NOT EXISTS rules_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS rules_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS timeout_action TEXT NOT NULL DEFAULT 'none';
